// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteArticle(arg1:string):Promise<string>;

export function FetchArticles():Promise<string>;

export function GetLocation():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SaveArticle(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetLocation(arg1:string):Promise<string>;

export function StartP2PNode():Promise<string>;

export function StopP2PNode():Promise<string>;
