// src/placeholders/articles.ts
import type { Article, Edition, PoliticalBias } from "@/types";

/**
 * Placeholder articles for development, testing, and UI previews.
 * All optional fields are set with null or sensible defaults.
 */
export const PLACEHOLDER_ARTICLES: Article[] = [
	{
		id: "1",
		title: "International Politics Today",
		content: "A quick overview of global political trends.",
		url: "#",
		source: "Global News Network",
		sourceDomain: "globalnews.example.com",
		sourceType: "rss",
		summary: "Highlights of international political events.",
		image: null,
		mobileUrl: null,
		sourceCountry: null,
		categories: ["politics", "international"],
		tags: ["policy", "diplomacy"],
		language: "en",
		author: null,
		publishedAt: new Date().toISOString(),
		edition: "international" as Edition,
		confidence: 0.8,
		analyzed: false,
		ipfsHash: null,
		raw: null,
		sourceMeta: { name: "Global News Network", bias: "left", confidence: 0.8 },
		fetchedAt: new Date().toISOString(),
	},
	{
		id: "2",
		title: "Tech Giants and Regulation",
		content: "How big tech is shaping our lives and legislation.",
		url: "#",
		source: "Tech Daily",
		sourceDomain: "techdaily.example.com",
		sourceType: "rss",
		summary: "Examining regulatory impacts on major tech companies.",
		image: null,
		mobileUrl: null,
		sourceCountry: "US",
		categories: ["technology", "policy"],
		tags: ["legislation", "innovation"],
		language: "en",
		author: null,
		publishedAt: new Date().toISOString(),
		edition: "us" as Edition,
		confidence: 0.9,
		analyzed: false,
		ipfsHash: null,
		raw: null,
		sourceMeta: { name: "Tech Daily", bias: "center", confidence: 0.9 },
		fetchedAt: new Date().toISOString(),
	},
	{
		id: "3",
		title: "Local Economy Insights",
		content: "Understanding the economic shifts in Korea.",
		url: "#",
		source: "Korean Economic Review",
		sourceDomain: "ker.example.kr",
		sourceType: "rss",
		summary: "An analysis of local market trends and financial shifts.",
		image: null,
		mobileUrl: null,
		sourceCountry: "KR",
		categories: ["economy", "finance"],
		tags: ["markets", "business"],
		language: "ko",
		author: null,
		publishedAt: new Date().toISOString(),
		edition: "kr" as Edition,
		confidence: 0.7,
		analyzed: false,
		ipfsHash: null,
		raw: null,
		sourceMeta: { name: "Korean Economic Review", bias: "right", confidence: 0.8 },
		fetchedAt: new Date().toISOString(),
	},
	{
		id: "4",
		title: "Climate Change and Policy",
		content: "What governments are doing about climate change.",
		url: "#",
		source: "Environmental Watch",
		sourceDomain: "envwatch.example.com",
		sourceType: "rss",
		summary: "Policy measures and global agreements on climate change.",
		image: null,
		mobileUrl: null,
		sourceCountry: null,
		categories: ["environment", "policy"],
		tags: ["climate", "sustainability"],
		language: "en",
		author: null,
		publishedAt: new Date().toISOString(),
		edition: "international" as Edition,
		confidence: 0.85,
		analyzed: false,
		ipfsHash: null,
		raw: null,
		sourceMeta: { name: "Environmental Watch", bias: "left", confidence: 0.85 },
		fetchedAt: new Date().toISOString(),
	},
	{
		id: "5",
		title: "Sports Highlights",
		content: "Recent games and results from major leagues.",
		url: "#",
		source: "Sports Network",
		sourceDomain: "sportsnet.example.com",
		sourceType: "rss",
		summary: "Top sporting events and scores from the past week.",
		image: null,
		mobileUrl: null,
		sourceCountry: "US",
		categories: ["sports"],
		tags: ["scores", "highlights"],
		language: "en",
		author: null,
		publishedAt: new Date().toISOString(),
		edition: "us" as Edition,
		confidence: 0.9,
		analyzed: false,
		ipfsHash: null,
		raw: null,
		sourceMeta: { name: "Sports Network", bias: "center", confidence: 0.9 },
		fetchedAt: new Date().toISOString(),
	},
	{
		id: "6",
		title: "Cultural Trends in Asia",
		content: "Exploring emerging trends in art and lifestyle.",
		url: "#",
		source: "Asia Lifestyle",
		sourceDomain: "asialifestyle.example.kr",
		sourceType: "rss",
		summary: "Insights into contemporary cultural movements across Asia.",
		image: null,
		mobileUrl: null,
		sourceCountry: "KR",
		categories: ["culture", "lifestyle"],
		tags: ["art", "fashion", "trends"],
		language: "ko",
		author: null,
		publishedAt: new Date().toISOString(),
		edition: "kr" as Edition,
		confidence: 0.8,
		analyzed: false,
		ipfsHash: null,
		raw: null,
		sourceMeta: { name: "Asia Lifestyle", bias: "right", confidence: 0.8 },
		fetchedAt: new Date().toISOString(),
	},
];
