import type { Source } from "@/types";

export const DEFAULT_SOURCES: Source[] = [
	{
		name: "NewsAPI",
		endpoint: "https://newsapi.org/v2/top-headlines?country=us&apiKey=YOUR_KEY",
		instructions: "Sign up for a free API key at NewsAPI and replace YOUR_KEY",
		apiLink: "https://newsapi.org/docs/endpoints/top-headlines",
		enabled: false,
		requiresApiKey: true,
		category: "news",
		authType: "apiKey",
		parser: "json",
		normalizer: "json",
	},
	{
		name: "The Guardian Open Platform",
		endpoint: "https://content.guardianapis.com/search?api-key=YOUR_KEY",
		instructions: "Requires free API key from The Guardian Open Platform",
		apiLink: "https://open-platform.theguardian.com/documentation/",
		enabled: false,
		requiresApiKey: true,
		category: "news",
		authType: "apiKey",
		parser: "json",
		normalizer: "json",
	},
	{
		name: "New York Times Top Stories",
		endpoint: "https://api.nytimes.com/svc/topstories/v2/home.json?api-key=YOUR_KEY",
		instructions: "Requires free API key from NYT Developer Portal",
		apiLink: "https://developer.nytimes.com/apis",
		enabled: false,
		requiresApiKey: true,
		category: "news",
		authType: "apiKey",
		parser: "json",
		normalizer: "json",
	},

	// Free / no API key required sources
	{
		name: "GDELT",
		endpoint: "https://api.gdeltproject.org/api/v2/doc/doc?query=world&mode=artlist&format=json",
		instructions: "No API key required; returns JSON feed with appropriate fields.",
		apiLink: "https://blog.gdeltproject.org/gdelt-2-0-our-global-world-in-realtime/",
		enabled: true,
		requiresApiKey: false,
		category: "news",
		authType: "none",
		parser: "json",
		normalizer: "gdelt",
	},
	{
		name: "Reddit /r/news JSON",
		endpoint: "https://www.reddit.com/r/news/.json",
		instructions: "Public JSON feed, no API key required; rate‑limits apply",
		apiLink: "https://www.reddit.com/dev/api/",
		enabled: true,
		requiresApiKey: false,
		category: "social",
		authType: "none",
		parser: "json",
		normalizer: "reddit",
	},
	{
		name: "BBC News RSS",
		endpoint: "http://feeds.bbci.co.uk/news/rss.xml",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "CNN RSS",
		endpoint: "http://rss.cnn.com/rss/edition.rss",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "Financial Times RSS",
		endpoint: "https://www.ft.com/?format=rss",
		instructions: "RSS feed, no API key required (FT may require subscription)",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "Al Jazeera All News RSS",
		endpoint: "https://www.aljazeera.com/xml/rss/all.xml",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "Reuters Top News RSS",
		endpoint: "http://feeds.reuters.com/reuters/topNews",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "Associated Press RSS",
		endpoint: "https://apnews.com/rss",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "NPR News RSS",
		endpoint: "https://www.npr.org/rss/rss.php?id=1001",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "The Verge RSS",
		endpoint: "https://www.theverge.com/rss/index.xml",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "TechCrunch RSS",
		endpoint: "http://feeds.feedburner.com/TechCrunch/",
		instructions: "RSS feed, no API key required",
		enabled: true,
		requiresApiKey: false,
		category: "rss",
		authType: "none",
		parser: "rss",
		normalizer: "rss",
	},
	{
		name: "Hacker News JSON",
		endpoint: "https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty",
		instructions: "Public JSON feed, no API key required; returns story IDs",
		apiLink: "https://github.com/HackerNews/API",
		enabled: true,
		requiresApiKey: false,
		category: "tech",
		authType: "none",
		parser: "json",
		normalizer: "hn",
	},
];
