// frontend/src/constants/sources.ts
import type { Source } from "@/types";

export const DEFAULT_SOURCES: Source[] = [
	// {
	// 	name: "NewsAPI",
	// 	endpoint: "https://newsapi.org/v2/top-headlines?country=us&apiKey=YOUR_KEY",
	// 	instructions: "Sign up for a free API key at NewsAPI and replace YOUR_KEY",
	// 	apiLink: "https://newsapi.org/docs/endpoints/top-headlines",
	// 	enabled: false,
	// 	requiresApiKey: true,
	// 	category: "news",
	// 	authType: "apiKey",
	// 	parser: "json",
	// 	normalizer: "json",
	// 	bias: "center",
	// 	confidence: 0.8,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["international", "top-headlines"],
	// 	rateLimitPerMinute: 100,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "The Guardian Open Platform",
	// 	endpoint: "https://content.guardianapis.com/search?api-key=YOUR_KEY",
	// 	instructions: "Requires free API key from The Guardian Open Platform",
	// 	apiLink: "https://open-platform.theguardian.com/documentation/",
	// 	enabled: false,
	// 	requiresApiKey: true,
	// 	category: "news",
	// 	authType: "apiKey",
	// 	parser: "json",
	// 	normalizer: "json",
	// 	bias: "left",
	// 	confidence: 0.9,
	// 	language: "en",
	// 	region: "UK",
	// 	tags: ["international", "politics", "news"],
	// 	rateLimitPerMinute: 100,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "New York Times Top Stories",
	// 	endpoint: "https://api.nytimes.com/svc/topstories/v2/home.json?api-key=YOUR_KEY",
	// 	instructions: "Requires free API key from NYT Developer Portal",
	// 	apiLink: "https://developer.nytimes.com/apis",
	// 	enabled: false,
	// 	requiresApiKey: true,
	// 	category: "news",
	// 	authType: "apiKey",
	// 	parser: "json",
	// 	normalizer: "json",
	// 	bias: "left",
	// 	confidence: 0.9,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["top-stories", "news"],
	// 	rateLimitPerMinute: 100,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// Free / no API key required sources
	{
		name: "GDELT",
		endpoint: "https://api.gdeltproject.org/api/v2/doc/doc?query=world&mode=artlist&format=json",
		instructions: "No API key required; returns JSON feed with appropriate fields.",
		apiLink: "https://blog.gdeltproject.org/gdelt-2-0-our-global-world-in-realtime/",
		enabled: true,
		requiresApiKey: false,
		category: "news",
		authType: "none",
		parser: "gdelt",
		normalizer: "gdelt",
		bias: "center",
		confidence: 0.95,
		language: "en",
		region: "US",
		tags: ["global", "real-time", "news"],
		rateLimitPerMinute: 0,
		lastUpdated: new Date("2025-01-01T00:00:00Z"),
	},
	// {
	// 	name: "Reddit /r/news JSON",
	// 	endpoint: "https://www.reddit.com/r/news/.json",
	// 	instructions: "Public JSON feed, no API key required; rate‑limits apply",
	// 	apiLink: "https://www.reddit.com/dev/api/",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "social",
	// 	authType: "none",
	// 	parser: "json",
	// 	normalizer: "reddit",
	// 	bias: "center",
	// 	confidence: 0.7,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["social", "community", "news"],
	// 	rateLimitPerMinute: 60,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "BBC News RSS",
	// 	endpoint: "http://feeds.bbci.co.uk/news/rss.xml",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://www.bbc.co.uk/news/help-41670342",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "center",
	// 	confidence: 0.85,
	// 	language: "en",
	// 	region: "UK",
	// 	tags: ["international", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "CNN RSS",
	// 	endpoint: "http://rss.cnn.com/rss/edition.rss",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://edition.cnn.com/services/rss/",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "left",
	// 	confidence: 0.85,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["international", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "Financial Times RSS",
	// 	endpoint: "https://www.ft.com/?format=rss",
	// 	instructions: "RSS feed, no API key required (FT may require subscription)",
	// 	apiLink: "https://help.ft.com/en/articles/what-is-the-financial-times-rss-feed",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "center",
	// 	confidence: 0.8,
	// 	language: "en",
	// 	region: "UK",
	// 	tags: ["finance", "international", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "Al Jazeera All News RSS",
	// 	endpoint: "https://www.aljazeera.com/xml/rss/all.xml",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://www.aljazeera.com/help/rss/",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "left",
	// 	confidence: 0.75,
	// 	language: "en",
	// 	region: "AE",
	// 	tags: ["international", "middle-east", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "Reuters Top News RSS",
	// 	endpoint: "http://feeds.reuters.com/reuters/topNews",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://www.reuters.com/resources/rss/",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "center",
	// 	confidence: 0.9,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["international", "finance", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "Associated Press RSS",
	// 	endpoint: "https://apnews.com/rss",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://apnews.com/hub/rss",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "center",
	// 	confidence: 0.9,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["international", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "NPR News RSS",
	// 	endpoint: "https://www.npr.org/rss/rss.php?id=1001",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://www.npr.org/rss/",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "left",
	// 	confidence: 0.85,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["international", "news", "radio"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "The Verge RSS",
	// 	endpoint: "https://www.theverge.com/rss/index.xml",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://www.theverge.com/rss",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "left",
	// 	confidence: 0.8,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["technology", "news", "gadgets"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "TechCrunch RSS",
	// 	endpoint: "http://feeds.feedburner.com/TechCrunch/",
	// 	instructions: "RSS feed, no API key required",
	// 	apiLink: "https://techcrunch.com/rssfeeds/",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "rss",
	// 	authType: "none",
	// 	parser: "rss",
	// 	normalizer: "rss",
	// 	bias: "center",
	// 	confidence: 0.8,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["technology", "startups", "news"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
	// {
	// 	name: "Hacker News JSON",
	// 	endpoint: "https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty",
	// 	instructions: "Public JSON feed, no API key required; returns story IDs",
	// 	apiLink: "https://github.com/HackerNews/API",
	// 	enabled: true,
	// 	requiresApiKey: false,
	// 	category: "tech",
	// 	authType: "none",
	// 	parser: "json",
	// 	normalizer: "hn",
	// 	bias: "center",
	// 	confidence: 0.75,
	// 	language: "en",
	// 	region: "US",
	// 	tags: ["tech", "community", "startups"],
	// 	rateLimitPerMinute: 0,
	// 	lastUpdated: new Date("2025-01-01T00:00:00Z"),
	// },
];
