// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddDebugLog(arg1:string,arg2:string,arg3:Record<string, any>):Promise<string>;

export function AppDeleteStatus():Promise<string>;

export function AppStatus():Promise<string>;

export function AppUpdateStatus(arg1:string):Promise<string>;

export function DeleteAnalyzedArticle(arg1:string):Promise<string>;

export function DeleteFederatedArticle(arg1:string):Promise<string>;

export function DeleteLocalArticle(arg1:string):Promise<string>;

export function FetchAnalyzedArticles():Promise<string>;

export function FetchArticlesBySources(arg1:Array<main.Source>):Promise<main.ArticlesBySource>;

export function FetchDebugLogs():Promise<string>;

export function FetchFederatedArticles():Promise<string>;

export function FetchLocalArticles():Promise<string>;

export function GetLocation():Promise<string>;

export function LoadSources():Promise<Array<main.Source>>;

export function OpenAbout():Promise<void>;

export function OpenSettings():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveAnalyzedArticle(arg1:Record<string, any>):Promise<string>;

export function SaveFederatedArticle(arg1:Record<string, any>):Promise<string>;

export function SaveLocalArticle(arg1:Record<string, any>):Promise<string>;

export function SaveSources(arg1:Array<main.Source>):Promise<void>;

export function SetLocation(arg1:string):Promise<string>;

export function StartP2PNode():Promise<string>;

export function StopP2PNode():Promise<string>;
