// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDebugLog(arg1) {
  return window['go']['main']['App']['AddDebugLog'](arg1);
}

export function AppDeleteStatus() {
  return window['go']['main']['App']['AppDeleteStatus']();
}

export function AppStatus() {
  return window['go']['main']['App']['AppStatus']();
}

export function AppUpdateStatus(arg1) {
  return window['go']['main']['App']['AppUpdateStatus'](arg1);
}

export function DeleteAnalyzedArticle(arg1) {
  return window['go']['main']['App']['DeleteAnalyzedArticle'](arg1);
}

export function DeleteFederatedArticle(arg1) {
  return window['go']['main']['App']['DeleteFederatedArticle'](arg1);
}

export function DeleteLocalArticle(arg1) {
  return window['go']['main']['App']['DeleteLocalArticle'](arg1);
}

export function FetchAnalyzedArticles() {
  return window['go']['main']['App']['FetchAnalyzedArticles']();
}

export function FetchArticlesBySources(arg1) {
  return window['go']['main']['App']['FetchArticlesBySources'](arg1);
}

export function FetchDebugLogs() {
  return window['go']['main']['App']['FetchDebugLogs']();
}

export function FetchFederatedArticles() {
  return window['go']['main']['App']['FetchFederatedArticles']();
}

export function FetchLocalArticles() {
  return window['go']['main']['App']['FetchLocalArticles']();
}

export function GetLocation() {
  return window['go']['main']['App']['GetLocation']();
}

export function LoadSources() {
  return window['go']['main']['App']['LoadSources']();
}

export function OpenAbout() {
  return window['go']['main']['App']['OpenAbout']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveAnalyzedArticle(arg1) {
  return window['go']['main']['App']['SaveAnalyzedArticle'](arg1);
}

export function SaveFederatedArticle(arg1) {
  return window['go']['main']['App']['SaveFederatedArticle'](arg1);
}

export function SaveLocalArticle(arg1) {
  return window['go']['main']['App']['SaveLocalArticle'](arg1);
}

export function SaveSources(arg1) {
  return window['go']['main']['App']['SaveSources'](arg1);
}

export function SetLocation(arg1) {
  return window['go']['main']['App']['SetLocation'](arg1);
}

export function StartP2PNode() {
  return window['go']['main']['App']['StartP2PNode']();
}

export function StopP2PNode() {
  return window['go']['main']['App']['StopP2PNode']();
}
