// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppStatus():Promise<string>;

export function DeleteArticle(arg1:string):Promise<string>;

export function FetchAnalyzedArticles():Promise<string>;

export function FetchArticles():Promise<string>;

export function FetchFederatedArticles():Promise<string>;

export function FetchLocalArticles():Promise<string>;

export function GetLocation():Promise<string>;

export function LoadSources():Promise<Array<main.Source>>;

export function OpenAbout():Promise<void>;

export function OpenSettings():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveArticle(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveSources(arg1:Array<main.Source>):Promise<void>;

export function SetLocation(arg1:string):Promise<string>;

export function StartP2PNode():Promise<string>;

export function StopP2PNode():Promise<string>;
