// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppStatus() {
  return window['go']['main']['App']['AppStatus']();
}

export function DeleteArticle(arg1) {
  return window['go']['main']['App']['DeleteArticle'](arg1);
}

export function FetchAnalyzedArticles() {
  return window['go']['main']['App']['FetchAnalyzedArticles']();
}

export function FetchArticles() {
  return window['go']['main']['App']['FetchArticles']();
}

export function FetchFederatedArticles() {
  return window['go']['main']['App']['FetchFederatedArticles']();
}

export function FetchLocalArticles() {
  return window['go']['main']['App']['FetchLocalArticles']();
}

export function GetLocation() {
  return window['go']['main']['App']['GetLocation']();
}

export function LoadSources() {
  return window['go']['main']['App']['LoadSources']();
}

export function OpenAbout() {
  return window['go']['main']['App']['OpenAbout']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveArticle(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveArticle'](arg1, arg2, arg3, arg4);
}

export function SaveSources(arg1) {
  return window['go']['main']['App']['SaveSources'](arg1);
}

export function SetLocation(arg1) {
  return window['go']['main']['App']['SetLocation'](arg1);
}

export function StartP2PNode() {
  return window['go']['main']['App']['StartP2PNode']();
}

export function StopP2PNode() {
  return window['go']['main']['App']['StopP2PNode']();
}
